services:
  - type: web
    name: office-transactions
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'node server.js'
    envVars:
      - key: NODE_VERSION
        value: 14
    autoDeploy: true
